name: Update

on:
  schedule:
    - cron:  '08 7 * * 3'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.email "bot@modm.io"
          git config --global user.name "modm update bot"
      - name: Run update.py script
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh api --silent -X PUT repos/${GITHUB_REPOSITORY}/actions/workflows/update.yml/enable
          python3 update.py
      - name: Git push
        run: |
          git push origin main
